=== kate-novik/JD2016-course/src/by/it/novik/jd02_07/payments/payments.dtd
<?xml version="1.0" encoding="UTF-8" ?>
        <!ELEMENT Rolls (Roll)+>
        <!ELEMENT Roll (Users)+>
        <!ATTLIST Roll
                idRoll ID
                name CDATA #REQUIRED>
        <!ELEMENT Users (User)+>
        <!ELEMENT User (First_Name, Middle_Name, Last_Name, Passport,
                Address, Phone, Email, Nickname, Password, Accounts*)>
        <!ATTLIST User ID ID #REQUIRED>
        <!ELEMENT First_Name (#PCDATA)>
        <!ELEMENT Middle_Name (#PCDATA)>
        <!ELEMENT Last_Name (#PCDATA)>
        <!ELEMENT Passport (#PCDATA)>
        <!ELEMENT Address (#PCDATA)>
        <!ELEMENT Phone (#PCDATA)>
        <!ELEMENT Email (#PCDATA)>
        <!ELEMENT Nickname (#PCDATA)>
        <!ELEMENT Password (#PCDATA)>
        <!ELEMENT Accounts (account)*>
        <!ELEMENT account (Amount,State,Payments*)>
        <!ATTLIST account idAccount ID #REQUIRED
                state CDATA #REQUIRED>
        <!ELEMENT Amount (#PCDATA)>
        <!ELEMENT State (#PCDATA)>
        <!ELEMENT Payments (payment)*>
        <!ELEMENT payment (Source,Description,Destination,Date,Amount_p)>
        <!ATTLIST payment idPayment ID #REQUIRED>
        <!ELEMENT Source (#PCDATA)>
        <!ELEMENT Description (#PCDATA)>
        <!ELEMENT Destination (#PCDATA)>
        <!ELEMENT Date (#PCDATA)>
        <!ELEMENT Amount_p (#PCDATA)>

=== kate-novik/JD2016-course/src/by/it/novik/jd02_07/payments/payments.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Rolls SYSTEM "payments.dtd" >
<Rolls>
    <Roll idRoll="1" name="Clients">
        <Users>
            <User ID="16">
                <First_Name>
                    Иван
                </First_Name>
                <Middle_Name>
                    Иванович
                </Middle_Name>
                <Last_Name>
                    Иванов
                </Last_Name>
                <Passport>
                    MC241234, 21.02.2015
                </Passport>
                <Address>
                    г.Минск, ул. Глебки, 5-15
                </Address>
                <Phone>
                    +375447512345
                </Phone>
                <Email>
                    ivanov@mail.ru
                </Email>
                <Nickname>
                    iv_ivan
                </Nickname>
                <Password>
                    zaq1@WSX
                </Password>
                <Accounts>
                    <account idAccount="123456" state="Working">
                        <Amount>
                            235
                        </Amount>
                        <Payments>
                            <payment idPayment="67853">
                                <Source>
                                    23456789
                                </Source>
                                <Description>
                                    Оплата за воду
                                </Description>
                                <Destination>
                                    231456789
                                </Destination>
                                <Date>
                                    25.06.2016
                                </Date>
                                <Amount_p>
                                    20
                                </Amount_p>
                            </payment>
                        </Payments>
                    </account>
                </Accounts>
            </User>
        </Users>
    </Roll>
    <Roll idRoll="2" name="Admin">
        <Users>
            <User ID="34">
                <First_Name>
                    Петр
                </First_Name>
                <Middle_Name>
                    Иванович
                </Middle_Name>
                <Last_Name>
                    Зеленков
                </Last_Name>
                <Passport>
                    MC256678, 02.04.2015
                </Passport>
                <Address>
                    г.Минск, ул. Шаранговича, 4-15
                </Address>
                <Phone>
                    +375296753427
                </Phone>
                <Email>
                    zelenkov@mail.ru
                </Email>
                <Nickname>
                    p_zelenkov
                </Nickname>
                <Password>
                    cde3$RRV
                </Password>
            </User>
        </Users>
    </Roll>
</Rolls>
